### PR TITLE
.exe removal in examples + anonymous note

### PR DESCRIPTION
**Pull request by weq**
#4318 can be closed.

Also added information about the fact that Azure DevOps doesn't support anonymous authentication since PAT is the ONLY method for accessing when using as PS repo.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@weq : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@chasewilson Could you review this pull request? Thanks.

**Comment by mijacobs** [comment]
@ktoliver @juliakm and @ramiMSFT own this article now (we've updated the article metadata, but this fork was created before that happened)

**Comment by PRMerger7** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ramiMSFT, you can only sign off in the main PR conversation, not in review comments.

**Comment by ktoliver** [comment]
@mijacobs Thanks, and thank you and @juliakm for your help with the PRs today. 👍 👍

**Pull request merged**
