### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@JiayueHu : Thanks for your contribution! The author, @gloridelmorales, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@openpublishbuild : Thanks for your contribution! The author, @gloridelmorales, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@openpublishbuild : Thanks for your contribution! The author, @kaelli, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@openpublishbuild : Thanks for your contribution! The author, @gloridelmorales, has been notified to review your proposed change.

**Pull request merged**
