### PR TITLE
(GH-4369) Set correct path to node

### LINKED ISSUE #4369: Invalid path to node
The path to node is not correct, see https://github.com/bbtsoftware/docker-azure-devops-agent/issues/8.

### PR DESCRIPTION
**Pull request by x-jokay**
Sets the correct path to node.

Fixes #4369.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@x-jokay : Thanks for your contribution! The author, @juliobbv, has been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
This already got fixed. Thanks for your contribution anyhow!

**Comment by pascalberger** [comment]
@vtbassmatt Where has this been fixed? Seems to be still the same to me [here](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md#l344) and on the [published docs.microsoft.com] page

**Comment by vtbassmatt** [comment]
My mistake, it's not fixed yet.

**Pull request closed without merging**
