### PR TITLE
Updating React and Vue instructions

### PR DESCRIPTION
**Pull request by jlooper**
I also moved this area directly under Angular, to cluster the instructions for these three frameworks.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jlooper : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by jlooper** [comment]
hi @andyjlewis, is there something I need to tweak or sign to help push this forward? Thanks!

**Comment by steved0x** [comment]
@jlooper I sent you an email, I am closing this PR and making a new one to get these changes incorporated. Thank you again for your contribution and sorry for the great delay.

**Comment by jlooper** [comment]
Yay! Thank you! We were just brought up to speed on how to better make PRs to contribute to the docs, very nice process. I’ll do more soon!

Best,
Jen

**Pull request closed without merging**
