### PR TITLE
Update VSTS REST API URL in authentication-guidance.md

### PR DESCRIPTION
**Pull request by eriawan**
Update VSTS REST API URL in authentication-guidance.md, because previous URL is not valid anymore (404/not found). Also enable URL in the table of application types and descriptions above.

### CODE REVIEW

**Comment by eriawan** [comment]
@steved0x and @elbatk 

Just to confirm, it's been 3 days. Any update on this PR review? Do I need to add or update something?

**Comment by elbatk** [comment]
Sorry @eriawan , you're good to go :) thanks for updating this!

**Comment by eriawan** [comment]
Thanks @elbatk ! 👍

**Comment by eriawan** [comment]
hi @elbatk , this change hasn't reflected in the online or live docs.

When will this change go live?

**Comment by elbatk** [comment]
I'm making this update manually as the automatic transfer from this repo seems to have goofed on this one. Should be live by EOD today. Thanks again @eriawan

**Comment by eriawan** [comment]
thanks @elbatk !

**Pull request merged**
