### PR TITLE
Azure DevOps Demo Generator - Added Using-the-Generator page and related images

### PR DESCRIPTION
**Pull request by aksh-h**
Documentation is related to Azure DevOps Demo Generator. Closing issue https://github.com/MicrosoftDocs/vsts-docs/issues/5084

### CODE REVIEW

**Comment by aksh-h** [comment]
@WilliamAntonRohm - I have updated the document here for the issue raised #5084 , can you please look into this and approve?

**Comment by WilliamAntonRohm** [comment]
@aksh-h -- Akshay, thank you for your contribution.

@hsachinraj -- Sachin, please review this PR.

**Comment by aksh-h** [comment]
@hsachinraj udpated image alt text VSTS to Azure DevOps

**Comment by ktoliver** [comment]
Hi @hsachinraj - Is the pull request approved? The new article requires metadata, and it must meet [PR review quality criteria](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master) for publishing. Would you like the PR reviewer team to move the commit to the private repo, where you can add the metadata and verify the update by using staging and validation? Thanks.

**Comment by PRMerger10** [comment]
@aksh-h : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mijacobs** [comment]
Adding @steved0x

**Comment by ktoliver** [comment]
@steved0x @mijacobs @hsachinraj - Could you indicate what action to take on this PR from August 2019?

Merge the PR: `#sign-off`
Close the PR: `#please-close`
Wait on the PR: `#hold-off`

Thanks!

**Comment by steved0x** [comment]
Closing since this PR has been moved to the private repo
https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/890

**Pull request closed without merging**
