### PR TITLE
fix: Add language to codefence

### PR DESCRIPTION
**Pull request by nschonni**
- mostly adding `xml` and fixing some minor formatting that the syntax highlighting showed
- ps replaced with powershell for better VS Code highlighting

Still seeing some big diffs from file encoding, but if you switch to the "rich" diff it shows the actual change

### CODE REVIEW

**Comment by steved0x** [comment]
@nschonni What's the benefit of using powershell instead of ps for the code fences for those samples? Something to do with VS Code? Can you put a screenshot of the differences here if you can, before I pass this PR along. Thank you!

**Comment by nschonni** [comment]
@steved0x Looks like GitHub also doesn't recognize `ps` as a valid language ID either. See https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/proxy.md#tab/windows vs the "Rich Diff" in the PR

**Comment by nschonni** [comment]
@steved0x did you need any other info?

**Comment by steved0x** [comment]
@nschonni I'm merging this, thank you!

**Pull request merged**
