### PR TITLE
Removing non-factual statements and bad guidance

### PR DESCRIPTION
**Pull request by StingyJack**
https://github.com/MicrosoftDocs/vsts-docs/issues/4144

### CODE REVIEW

**Comment by PRMerger9** [comment]
@StingyJack : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@StingyJack : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@steved0x: I'm sorry - only the author of this article, @apawast, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by steved0x** [comment]
Thank you @StingyJack

**Comment by PRMerger18** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
