### PR TITLE
fix: cmd for macOS, use echo -n for PAT base64 token

### LINKED ISSUE #2612: How to auth using PAT over 90 days ?
Hello,

As the documentation said, we can use PAT to be able to avoid renew the token every 90 days to access to npm feeds. But when I follow the documentation, I still have a 401 on `npm install`.

The documentation tell to add the following lines on `~/.npmrc`:

```
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:username=YOUR-USERNAME
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:_password=BASE64-ENCODED-PAT-GOES-HERE
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:email=YOUREMAIL@EXAMPLE.COM
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:always-auth=true
```

Questions:

1. The strange thing is the url for registry on `.npmrc` project file is not the same as decribe (eg: `registry=https://<organization>.pkgs.visualstudio.com/_packaging/<feed>/npm/registry/`)
2. What should I use as username? I did try the organization name, my email even the email prefix before the `@`, but nothing works...

I did try to set both URL, but nothing works...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=vsts&tabs=new-nav%2Cwindows)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

### PR DESCRIPTION
**Pull request by spike008t**
Fix wrong command on macOS/linux to generate the PAT base64 token.

Close #2612

### CODE REVIEW

**Comment by alexmullans** [comment]
@elbatk this is a good change and should go in. Can you look at the build failures and resolve/merge?

**Comment by elbatk** [comment]
There was a weird error with the build here but I don't think that there is an issue with this change. @spike008t , thanks for your contribution. I can either port your change over to our private repo and get it pushed to master, or if you want the GitHub kudos, you could try pushing a change to this branch (just a blank space, or something) to get another build to trigger and see if that one would work? What would you like to do?

**Comment by elbatk** [comment]
Hmm, I really am not sure what this error is. Adding @erickson-doug and @steved0x to take a look? It may be because you're pushing from a forked organization but I'm not sure?

**Comment by elbatk** [comment]
@steved0x not sure what's going on here /: are builds fixed?

**Comment by steved0x** [comment]
@spike008t @elbatk @alexmullans The vsts-docs repo issues are resolved, I ave fixed this PR and I am merging it now. Thank you for your contribution @spike008t

**Review by kaycoinsUSA — COMMENTED** [review]
Done

**Pull request merged**
