### PR TITLE
Update powershell.md

### PR DESCRIPTION
**Pull request by kevbite**
Updating information on how to allow OAuth Token to be used. (This seemed to have moved)

### CODE REVIEW

**Comment by chcdggrs** [comment]
public interface HarvestableConnection

**Comment by steved0x** [comment]
@kevbite Thank you for your contribution. @andyjlewis Can you review this?

**Comment by nschonni** [comment]
In TFS 2017.3.1 the current text is correct and is talking about
image

**Comment by kevbite** [comment]
Ah, see we're using VSTS, and the article says it's applicable to `VSTS | TFS 2018 | TFS 2017 | TFS 2015` and also references.

As within VSTS, it's in the agent phase

image

**Comment by andyjlewis** [comment]
Thank you for the pull request. We need to handle this change differently because it is different depending on TFS version or VSTS. I've got a backlog item tracking it.

**Pull request closed without merging**
