### PR TITLE
Added links to API service health references

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
The change is based on the issue #6231
Fixes https://github.com/MicrosoftDocs/vsts-docs/issues/6231

### CODE REVIEW

**Comment by PRMerger20** [comment]
@SebastianSchuetze : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@chcomley - can you review?  (note that the URLs will need the loc 'en-us/' removed before this can be merged). thanks!

**Comment by chcomley** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
