### PR TITLE
Add "set-variables-in-scripts" file

### PR DESCRIPTION
**Pull request by shayki5**
Now only in the release variables page, there is a tutorial about how to use the variables on Batch/PowerShell/Shell.
It's would be great if it will also available in the Build variables page.

### CODE REVIEW

**Comment by andyjlewis** [comment]
Thanks for the PR. We had this section in here, but it's been moved here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#set-in-script

**Comment by shayki5** [comment]
Ok, I missed this page :) but why is also exist on https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch ?

**Comment by shayki5** [comment]
Ok, I missed this page :) but why is also exist on https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch ?

**Comment by andyjlewis** [comment]
@alexhomer1 might be able to advise on that question.

**Pull request closed without merging**
