### PR TITLE
(GH-4366) Add missing libraries

### LINKED ISSUE #4366: Missing libraries
There seems to be missing some libraries to get the agent using docker to work, see https://github.com/bbtsoftware/docker-azure-devops-agent/issues/6.

### PR DESCRIPTION
**Pull request by x-jokay**
Added missing libraries.

Fixes #4366.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@x-jokay : Thanks for your contribution! The author, @juliobbv, has been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
Fixed elsewhere - thanks for your contribution though!

**Comment by pascalberger** [comment]
@vtbassmatt Where has this been fixed? Seems to be still the same to me on the [master branch](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md#l344) and on the [published docs.microsoft.com](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux) page

**Comment by vtbassmatt** [comment]
@pascalberger apparently I'm not very good at GitHub today... thanks for pinging :)

**Pull request closed without merging**
