### PR TITLE
Update universal-packages.md

### PR DESCRIPTION
**Pull request by Thomas-Leung**
Fixed typo on an example and updated vstsFeedPublish attribute to clarify what it will take.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Thomas-Leung : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@chasewilson Could you review this pull request? Thank you.

**Comment by ktoliver** [comment]
@Thomas-Leung Would you take a moment to sign the CLA? Then we can review your pull request.

@juliakm I've added this PR as an example in an open bug:  https://ceapex.visualstudio.com/Engineering/_workitems/edit/168950

#hold-off until the CLA is signed by the contributor

Thanks!

**Comment by ktoliver** [comment]
Unfortunately, this PR isn't mergeable unless the contributor signs the CLA. The PR was opened in December. If the content team finds the update helpful, you might choose to implement it in the private repo. Then, we would close this PR.

**Comment by PRMerger9** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Thomas-Leung** [comment]
Sorry for the late response. The CLA has been signed.

**Comment by PRMerger14** [comment]
@Thomas-Leung : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Thomas-Leung : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @Thomas-Leung - It looks like your commits ended up with the same revisions that were approved by @juliakm and @ramimsft so we'll merge the PR.

**Pull request merged**
