### PR TITLE
update copy files for non windows agents

### PR DESCRIPTION
**Pull request by IsaGeoff**
Spent fucking forever trying to figure out why 0 files would copy before stumbling into the need to change the slashes.

### CODE REVIEW

**Comment by steved0x** [comment]
@IsaGeoff Sorry that you ran into trouble, and thank you for making the contribution to fix it! I will get this reviewed ASAP.

**Comment by vtbassmatt** [comment]
Not just macOS, but also Linux and BSD. It might be worth changing all the examples to forward slashes, since they'll also work on Windows.

**Comment by nschonni** [comment]
Sounds like a product bug for https://github.com/Microsoft/azure-pipelines-tasks

**Comment by steved0x** [comment]
This has been fixed in the docs, apologies for the long delay in looping back.

**Pull request closed without merging**
