### PR TITLE
Update @mentions

### PR DESCRIPTION
**Pull request by jesomekh**
We are doing work to add @mentions to all text fields on the work items form. Just adjusting this language to keep it generic to the form instead of specific to discussion.

### CODE REVIEW

**Comment by jesomekh** [comment]
@steved0x Oops, typo. Nope. My intention was for it to say "Use @mentions" !

**Comment by elbatk** [comment]
@jesomekh maybe make it "Use @mentions in work items and pull requests - VSTS and TFS" for some SEO help.

**Comment by jesomekh** [comment]
@elbatk Sure I like that better! I've made the changes :)

**Comment by elbatk** [comment]
@jesomekh merged :)

**Pull request merged**
