### PR TITLE
Corrected step numbers, smoothed flow

### PR DESCRIPTION
**Pull request by shutters527**
I'm brand new to Pipelines, thought these minor edits would have helped me move a bit quicker. Thanks!

### CODE REVIEW

**Comment by PRMerger17** [comment]
@shutters527 : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by steved0x** [comment]
@shutters527 Thank you for your contribution. I'm taking a look at these changes, do you have any objection to me pushing changes back into your branch (I'm going to make a copy in our private repo so i can stage it, in case I need to make some tweaks) before I merge it?

**Comment by shutters527** [comment]
Hi Steve-
Nope, go for it!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by PRMerger20** [comment]
@shutters527 : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by steved0x** [comment]
@shutters527 I made a few tweaks and I am merging it now. Thank you again for your contribution!

**Pull request merged**
