### PR TITLE
Bug in Publish python distribution to Azure Artifacts feed

### PR DESCRIPTION
**Pull request by miguelgfierro**
```
python -m twine upload -r "myTestProject/myTestFeed" --config-file $(PYPIRC_PATH) dist/*.whl
```
gets the error:

```
InvalidConfiguration: Missing 'myTestProject/myTestFeed' section from the configuration file
or not a complete URL in --repository-url.
```
this solves the problem:

```
python -m twine upload -r myTestFeed --config-file $(PYPIRC_PATH) dist/*.whl
```
see full trace https://msdata.visualstudio.com/DefaultCollection/AlgorithmsAndDataScience/_build/results?buildId=10828720&view=logs&j=836bd6c2-066c-5c38-d30d-e81e3a76d869&t=d8543af4-8a21-5f05-1956-5ba398eb8383

### CODE REVIEW

**Comment by PRMerger15** [comment]
@miguelgfierro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
cc @juliakm

**Comment by mijacobs** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@mijacobs: I'm sorry - only the author of this article, @chasewilson, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
