### PR TITLE
Update set-permissions.md

### PR DESCRIPTION
**Pull request by zanecop**
best security practices notes

### CODE REVIEW

**Comment by PRMerger15** [comment]
@zanecop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @chasewilson Could you review the proposed changes? Thanks.

**Comment by PRMerger18** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ramiMSFT** [comment]
@zanecop Thank you for your contribution. I made a slight change to your original contribution. We'll get this merge.

**Comment by ramiMSFT** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@ramiMSFT: I'm sorry - only the author of this article, @chasewilson, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by steved0x** [comment]
@ktoliver I accidentally merged this customer contribution instead of using PRMerger, I will do it the right way next time.

**Comment by ktoliver** [comment]
@steved0x Thanks! No worries. :)

**Pull request merged**
