### PR TITLE
Updated Publish Code Coverage Results task documentation

### LINKED ISSUE #4410: Missing pathToSources argument (PR added)
I've added a PR (https://github.com/MicrosoftDocs/vsts-docs/pull/4409) to include this information.

Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

### PR DESCRIPTION
**Pull request by Exodus**
Including the existing pathToSources argument (Label: Path to Source files).

This seems to be a very important piece of information required to better utilize this task since multiple tests reports either don't have absolute paths or have a distinct path due to ex. running inside a docker container in /app and the reports get extracted to $(System.DefaultWorkingDirectory) in the agent.

Info taken from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishCodeCoverageResultsV1/task.json#L47-L52

Resolves #4410

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Exodus : Thanks for your contribution! The author, @pboraMSFT, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @davidstaheli - Could you review the proposed changes? Thanks.

**Comment by Jak-MS** [comment]
@Exodus - it looks like there are now some branch conflicts in **docs/pipelines/tasks/test/publish-code-coverage-results.md**. can you address these? 

cc: @davidstaheli 

thanks.

**Comment by Jak-MS** [comment]
@Exodus - it looks like there are now some branch conflicts in **docs/pipelines/tasks/test/publish-code-coverage-results.md**. can you address these? 

cc: @davidstaheli 

thanks.

**Comment by PRMerger18** [comment]
@Exodus : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Exodus** [comment]
> @Exodus - it looks like there are now some branch conflicts in **docs/pipelines/tasks/test/publish-code-coverage-results.md**. If you address these, we can merge this. thanks.
> 
> cc: @davidstaheli
> 
> thanks.

@Jak-MS I have resolved the merge conflict and updated to the latest V2 task.json inputs.

**Comment by PRMerger19** [comment]
@Exodus : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
thanks @Exodus !  

@davidstaheli , can i get you to take another quick look and approve? thanks!

**Pull request merged**
