### PR TITLE
Adds sample yaml to the app signing docs

### PR DESCRIPTION
**Pull request by VitorRigoni**
This PR addresses #3347 by adding sample yaml to the app signing docs.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@VitorRigoni : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@VitorRigoni : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by chasewilson** [comment]
@VitorRigoni I'm really sorry about the late response, we've had some internal moves. It looks like you have a merge conflict I believe it was updated with what looks like the entire doc is the conflict?

**Comment by VitorRigoni** [comment]
Hi @chasewilson ! Oh, no worries, all good =)
The diff is definitely weird... My first diff didn't look like this, though. Looks like EOL changes... I'll investigate and sort this out.

**Comment by ktoliver** [comment]
Resolved the merge conflict (metadata had been updated).

@chasewilson Could you review the proposed changes? Thanks.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@chasewilson Could you review this pull request? Thanks much.

**Comment by juliakm** [comment]
#sign-off

**Pull request merged**
