### PR TITLE
Multiple jobParameters on JenkinsQueueJob Task

### PR DESCRIPTION
**Pull request by cmelo05**
Better explain how to input multiple parameters on jobParameters property inside Jenkins Queue Job Task from Azure Pipelines.

### CODE REVIEW

**Comment by cmelo05** [comment]
@RoopeshNair @ktoliver any updates on this PR?

**Comment by RoopeshNair** [comment]
@vijayma for queue Jenkins job

**Comment by cmelo05** [comment]
@vijayma any updates on this PR?

**Comment by ktoliver** [comment]
@vijayma - Would you be able to review the proposed changes and indicate whether the PR can be merged? Thanks.

**Comment by vijayma** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@vijayma: I'm sorry - only the author of this article, @RoopeshNair, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@cmelo05 Would you take a moment to sign the Contributor License Agreement (CLA)? Then, the PR can be merged. Thanks.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by cmelo05** [comment]
@ktoliver Just signed the CLA

**Pull request merged**
