### PR TITLE
Missing info about TypeScript

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
I ran into the problem not having TypeScript installed globally on my machine. In that case the command in the paragraph I changed would fail.

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
Seems like the build failed because of some permission problems on your system :-(

**Comment by steved0x** [comment]
@SebastianSchuetze Thank you for your contribution. We have had some trouble with syncing between this public repo and our private repo, which has been resolved, but has caused an issue with PRs submitted during the interval in which the problem was unresolved. One of the side effects is a lot of extra files added to the PR and also some merge conflicts.

Can you respond and let me know which file in this PR has your changes and I will get them merged, or if you wish to close this PR and create a new PR with your changes in a branch based off the latest upstream master that would work as well (although that is more trouble and I apologize for that)

Thank you again for your contribution.

**Comment by SebastianSchuetze** [comment]
Hi, of course. It was the following commit in the PR:

https://github.com/MicrosoftDocs/vsts-docs/pull/2632/commits/55ba390b284e8f08cb4ceca6e9d18c724365a3bd

**Comment by steved0x** [comment]
@SebastianSchuetze Thank you, there it was right at the bottom of the list too :)

I have made this change to our private repo and it should be live soon (and replicated back to this public repo).

**Pull request closed without merging**
