### PR TITLE
fixing markdown in secure-files.md

### PR DESCRIPTION
**Pull request by raydixon**
Fixing markdown in last section by adding new line between the heading and numbered list so the numbered list and formatting render correctly.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@raydixon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@steved0x: I'm sorry - only the author of this article, @gloridelmorales, @mijacobs, @thomps23, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
