### PR TITLE
Adjust nuget yaml docs

### PR DESCRIPTION
**Pull request by davidroberts63**
Work In Progress, wanting feedback on styling.

This is to adjust the current [NuGetCommand YAML documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts) to be in line with how to use it in YAML. Existing documentation looks to be from the perspective of the GUI pipeline builder.

Specific points to consider:
- At this point only the `restore` command doc has been fully adjusted, if the styling looks okay to you I'll do the rest.
- Using the `inputs` names (for 'Argument') instead of the general name seen in GUI
- I noticed the name and aliases in the [task.json](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetCommandV2/task.json) so I thought I'd put those in as well.
- Updated the example to be a YAML one, not a GUI one.
- Any feedback is acceptable, I'm here to help you out, not to change things up.

Very minor question:
I was trying to use the [GitHub markdown tables format](https://help.github.com/articles/organizing-information-with-tables/) but the VSCode markdown viewer was not making it 100% width. I'd rather try use that if anyone likes, but given it's narrower output I kept current. Does anyone know if the GHM tables would work in this instance?

### CODE REVIEW

**Comment by elbatk** [comment]
Hi @davidroberts63 , thank you for your efforts here! GHM tables work fine in our publishing system and are preferred to HTML. We definitely need to include YAML in this, but we can't remove the GUI version as there are people that still use that (even though we recommend YAML). In some docs we implement tabs to  show both methods side-by-side and that syntax is as follows:

# [YAML](#tab/yaml)

```yaml
- powershell: gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/environment-variables.txt

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
```

# [Designer](#tab/designer)

<designer content in here>

---

I may have to take your changes and put them into a branch from our publishing system so that I can get a preview site up, as these changes look like they could be tricky in format.

**Comment by davidroberts63** [comment]
I'll put in the tab setup you mentioned for GUI and YAML syntax, thank you for mentioning that. And I'll be curious how preview site looks. I'll work on that in the next several days.

Also, getting the CLA run by my employer's legal, simply letting you know I'm not ignoring it.

**Comment by ktoliver** [comment]
The PR is more than a year old and the CLA has not been signed. 

@steved0x - You removed the `stale` tag. Would you add a comment to show what action to take on this PR:

Merge the PR: `#sign-off`
Close the PR: `#please-close`

Thanks!

@kathrynEE @elbatk

**Comment by ktoliver** [comment]
The CLA hasn't been signed in 414 days; we'll close the pull request. If the PR contains helpful updates, the content team can implement via the private repository. Thanks.

**Pull request closed without merging**
