### PR TITLE
added precision around the max run time for a hosted agent

### PR DESCRIPTION
**Pull request by baywet**

### CODE REVIEW

**Comment by steved0x** [comment]
@baywet Thank you for your contribution, I have got this routed to the right folks - we may be about to make some other edits to this area so I am holding this PR for the moment, and I'll come back shortly as soon as I have an update.

**Comment by steved0x** [comment]
@baywet Sorry it took so long to get verification - I found out that paid jobs can run for 6 hours, and 30 minutes on the free tier. If you update your sentence to the below I can merge the PR:

`Can run jobs for up to 6 hours (30 minutes on the free tier).`

**Comment by baywet** [comment]
@steved0x no worries, thanks for double checking.
I updated the documentation.
However the experience we're getting (2 hosted pipelines, paid) is different from what's described now. Builds timeout after running for 60 minutes. Using Hosted VS 2017 agent, tenant name 2tolead

**Comment by steved0x** [comment]
@baywet Let me pass that along to the team and see what's going on. Thank you for the additional info.

**Comment by steved0x** [comment]
@baywet YES! I tried looking for it (build release isn't my area, mine is Git) and I couldn't find it. I'll assign a work item to that writer and see if we can get this clarified. Actually, if you can wait a day or so until this change goes live, and then go to the document and click "Give documentation feedback" and provide this feedback - coming from a customer it would have more weight than if I filed it myself. I'm going to go ahead and merge this. Thank you again and sorry it took so long to run down.

**Pull request merged**
