### PR TITLE
Update extension target images and copy

### PR DESCRIPTION
**Pull request by matthewisabel**
I'll loop through the rest and/or pull people in for the menus shortly

### CODE REVIEW

**Comment by PRMerger7** [comment]
@matthewisabel : Thanks for your contribution! The author, @elbatk, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@matthewisabel : Thanks for your contribution! The author, @elbatk, has been notified to review your proposed change.

**Comment by nschonni** [comment]
Might be good to do this in one of the moniker ranges, so people on <2019 can still see their correct values

**Comment by chcomley** [comment]
Hi @matthewisabel Is this still in the works? Can we please revisit, so we can close this out? Let me know how I can help, thanks!

**Comment by ktoliver** [comment]
Resolved the merge conflict. 

@chcomley - Is the PR ready to be merged? Thanks!

**Pull request closed without merging**
