### PR TITLE
Update .openpublishing.redirection.json

### PR DESCRIPTION
**Pull request by Banani-Rath**

### CODE REVIEW

**Comment by steved0x** [comment]
@Banani-Rath I am researching into this - every other instance in the file is set to false. I'm not sure why, so I am doing some research into it and will get back with you shortly. Thank you for your contribution!

**Comment by steved0x** [comment]
@Banani-Rath Per our conversation I am closing this PR, thank you!

**Comment by toki1314** [comment]
Exd

**Comment by toki1314** [comment]
Exd

**Pull request closed without merging**
