### PR TITLE
Download feature issue with version 0.14.0 and up

### PR DESCRIPTION
**Pull request by jontreynes**
Hey, there's an issue with using the provided code

```yaml
steps:
- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    command: download
    vstsFeed: 'fabrikamFeed'
    vstsFeedPackage: 'fabrikam-package'
    vstsPackageVersion: 1.0.0
    downloadDirectory: '$(Build.SourcesDirectory)\anotherfolder'
```

You need to provide the project id when using Azure DevOps 0.14.0 and up.

Example:

When you need to get the package with a command like so

az artifacts universal download --organization "" --project "NEW ARGUMENT" --feed "" --name "" --version "" --path .

It would be great if this extension added another argument to capture the project

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jontreynes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jontreynes** [comment]
@chasewilson - can you help me add the maintainer of the UniversalPackages@0 task extension. This PR will relay into a feature request as well

**Comment by jontreynes** [comment]
Ah, you can also provide the project alias rather than the project id

**Comment by ktoliver** [comment]
Hi @chasewilson - Could you review this pull request? Thanks.

**Comment by PRMerger19** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ramiMSFT** [comment]
@jontreynes Thank you for your contribution. Is this the extension you are referring to ([Link](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks)) when you said "When using Azure Artifacts with the Azure DevOps extension 0.14.0 and up"?

**Comment by PRMerger12** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ramiMSFT** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ramiMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
