### PR TITLE
Update DownloadPipelineArtifactV2.md

### PR DESCRIPTION
**Pull request by jahsu-MSFT**
Update old input names to the new input names
https://github.com/microsoft/azure-pipelines-tasks/issues/11835

### CODE REVIEW

**Comment by jborsecnik** [comment]
Hi @davidstaheli, can you review this PR?

Hi @jahsu-MSFT, are you a Microsoft employee?
	
Thank you!

**Comment by jahsu-MSFT** [comment]
@jborsecnik Thanks for coordinating. Yes, our team is working on Pipeline Artifacts tasks. Why?
@willsmythe @davidstaheli Please take a look when you get a chance. :) 
Thanks,

**Comment by jborsecnik** [comment]
Hi @jahsu-MSFT, there are two reasons: 

- First, it's preferred for Microsoft employees work in the private repos, so the content can be staged and validated by the current validation rules.  For more information, see [Should I work in a private or a public repo?](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) <br/><br/>If you need help getting set up to work in the private repo, see [Fork and clone a reposistory](https://review.docs.microsoft.com/en-us/help/contribute/fork-and-clone?branch=master).<br/><br/>
- Second, you should link your Microsoft and GitHub aliases. This helps us identify and locate you, and thereby smooth the flow of your PRs. See [Link your GitHub and Microsoft accounts](https://review.docs.microsoft.com/en-us/learn-docs/docs/git-setup-github-account?branch=master#link-your-github-and-microsoft-accounts).

Thanks.

**Comment by jahsu-MSFT** [comment]
@jborsecnik  I see. Thanks for clarifying. I don't usually work on doc repos and didn't  know there is public/private pairings.

**Pull request merged**
