### PR TITLE
Changed images in to reflect new UI

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
Changed images for the git command guidelines in pipelines

### CODE REVIEW

**Comment by PRMerger20** [comment]
@SebastianSchuetze : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@SebastianSchuetze : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by steved0x** [comment]
Topic that uses these images:
https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml

**Comment by SebastianSchuetze** [comment]
@andyjlewis I want to kindly ask, if there is any progress for this change?

**Pull request merged**
