### PR TITLE
Update yaml-schema.md

### PR DESCRIPTION
**Pull request by droessmj**
Specify the cron schedule is executed in UTC time

### CODE REVIEW

**Comment by PRMerger14** [comment]
@droessmj : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vtbassmatt** [comment]
This isn't correct, it's scheduled in the time set by the organization.

**Comment by droessmj** [comment]
Appreciate the feedback, but that statement directly conflicts with the behavior I experienced when working with this yesterday. 

Our organization runs with UTC-6, 
image, but I needed to set a schedule for 18:20 yesterday for it to trigger at 12:20PM CT. 

image

Let me know if you'd prefer I open an issue, but this PR was submitted in an attempt to reduce future occurrences. 

Only other potential impact I can come up with offhand is that the pool in use is a Windows Hosted Agent rather than a corporately hosted pool. Not sure if that would make a difference or not on scheduling?

**Comment by steved0x** [comment]
@droessmj It is UTC time, that is clarified [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers) but I think it is a good idea to update the comment like you did so I'm approving this PR.

**Comment by steved0x** [comment]
#sign-off

**Pull request merged**
