### PR TITLE
Added YAML schema reference to getting started 

### PR DESCRIPTION
**Pull request by calloncampbell**
This addresses issue #2094

### CODE REVIEW

**Comment by steved0x** [comment]
@calloncampbell Thank you for adding this link. Can you change the format of the link to this:

`[YAML schema reference](yaml-schema.md)`

And I will merge the PR.

Thank you,

Steve

**Comment by calloncampbell** [comment]
Hi @steved0x , I made the change as per your feedback.

**Comment by andyjlewis** [comment]
Let's move it to the bottom of the page and change the wording to "To learn what else you can do in YAML pipelines, see..."

**Comment by calloncampbell** [comment]
Sure I can do that if you like.

**Comment by calloncampbell** [comment]
Made the change. Do I need to submit another PR?

**Pull request closed without merging**
