### PR TITLE
chore: Cleanout root unreferenced DocFX files

### PR DESCRIPTION
**Pull request by nschonni**
These appear to be old testing files some of which have been updated through find/replace over time

### CODE REVIEW

**Comment by steved0x** [comment]
@nschonni It does look like that, but let me check when more folks are back in the office Monday before I merge.

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by nschonni** [comment]
@steved0x I've rebase this for the conflict

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by steved0x** [comment]
@nschonni I never was able to run down these files and I don't know if they are required (and I'm afraid to find out by removing them...) So I am going to leave them for now.

**Pull request closed without merging**
