### PR TITLE
Verify if you're using SSH

### PR DESCRIPTION
**Pull request by tekguy**
Not all developers use SSH, some use HTTPS. Added a section describing how to verify existing git urls.

### CODE REVIEW

**Comment by steved0x** [comment]
@tekguy Thank you for your contribution, I am reviewing it and will get back to you shortly. Please accept our apologies for this initial delay while we work though the initial backlog of contributions.

**Comment by steved0x** [comment]
@tekguy Sorry for the delay, we got behind on these. Can you move your bullet up into the important box so that it is the first bullet in the list, like below? Thank you.

>[!IMPORTANT]
> SSH URLs have changed. Old SSH URLs will continue to work through December 1, 2017. If you have already set up SSH, you will need to update your remote URLs:
> - Verify which remotes are using SSH by running `git remote -v` in your Git client.
> - Visit your repository on the web and select the **Clone** button in the upper right.
> - Select **SSH** and copy the new SSH URL.
> - In your Git client, run: ```git remote set-url <remote name, e.g. origin> <new SSH URL>```. Alternatively, in Visual Studio, go to **Repository Settings**, and edit your remotes.

**Comment by tekguy** [comment]
@steved0x  I've updated the PR. Thank you

**Comment by steved0x** [comment]
@tekguy I am merging this in, thank you!

**Comment by steved0x** [comment]
@tekguy I somehow merged in the change including the tags from the merge conflict, but I resolved it in https://github.com/MicrosoftDocs/vsts-docs/pull/154, sorry about that confusion and thanks again.

**Pull request merged**
