### PR TITLE
Running in Docker with Kubernetes

### PR DESCRIPTION
**Pull request by brunomartinspro**
This is a tutorial on how to setup Azure DevOps Agent with Docker running on Kubernetes.

**Why did i create this documentation**
I think its important to share knowledge on how you could setup the agents in kubernetes in a step by step tutorial.

**Why i choose to download previously the agent instead of the docker file**
Docker caches resources into layers, therefore it is faster to download it in the first hand and then copy it to the container. This facilitates building the docker container multiple times as well.

**Why i used the current date with milliseconds to create the Agent Name** 
It is easier to handle concurrency when scaling multiple pods, therefore all pods have unique agents capable of responding.

**Why i created a stop script**
When we scale down containers they emit a life cycle hook called "PreStop" that waits at max 30 seconds (https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) until it deletes the container, this allows enough time to delete the agent from the server. (More on https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)

### CODE REVIEW

**Comment by steved0x** [comment]
@brunomartinspro Thank you for this contribution, I am going to work with you and get this published. I need to stage it on our private repo and add some required metadata to the top. Before I do that I am going to give it a review, do you mind if I push changes to your branch and update this article?

**Comment by brunomartinspro** [comment]
> @brunomartinspro Thank you for this contribution, I am going to work with you and get this published. I need to stage it on our private repo and add some required metadata to the top. Before I do that I am going to give it a review, do you mind if I push changes to your branch and update this article?

@steved0x please do, feel free to make any changes needed, thank you very much 😁

**Comment by steved0x** [comment]
@brunomartinspro I'm in the process of editing this article and getting it reviewed. We do that in the private repo by pushing the commits from your branch into a branch there. We have some required metadata, including `author`, which is a GitHub alias for a Microsoft FTE responsible for GitHub issues, and `ms.author`, which must be a Microsoft FTE. However, `ms.author` can have multiple values, and while one value must be a Microsoft FTE, the other can be your email address. If you would like me to include that, please let me know and I will add it. I am setting myself (or possibly one of my team) as the value for `author` and `ms.author` so that the article will validate through our build process. Your will be credited for your contribution from your commits, and in your email address (if you wish to provide it). I'll keep you updated as the article goes through a review. Thank you again for your contribution.

**Comment by steved0x** [comment]
@brunomartinspro Do you see your article in the TOC as a sibling to this article:

[Running a self-hosted agent in Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)

Or perhaps as a new section in that article in the Windows section of that article? Please send me an email to steve.danielson@microsoft.com and we can continue the discussion there, might be easier than me leaving a lot of comments here :)

**Comment by brunomartinspro** [comment]
> @brunomartinspro Do you see your article in the TOC as a sibling to this article:
> 
> [Running a self-hosted agent in Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
> 
> Or perhaps as a new section in that article in the Windows section of that article?

Thank you for letting me contribute to this, sent you an email from hello@brunomartins.pro 😁

**Comment by ktoliver** [comment]
Hi @steved0x - Is this pull request still in progress? Thanks.

**Comment by steved0x** [comment]
@brunomartinspro I am closing this PR and sending you an email very shortly. We are releasing a feature soon called [Elastic self-hosted pools](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1221174) and this is the recommended solution by the Pipelines team for this issue. For that reason we are unable to add your new article at this time. I am sorry that it took so long to close the loop on this, and I want to thank you again for your contribution.

**Comment by brunomartinspro** [comment]
Glad this was added later on, the community really needed this! 💯 

[https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#use-azure-kubernetes-service-cluster](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#use-azure-kubernetes-service-cluster)

**Pull request closed without merging**
