### PR TITLE
allow-list-ip-url.md: fix vs-ssh.visualstudio.com domain

### PR DESCRIPTION
**Pull request by congyiwu**
The actual domain is vs-ssh.visualstudio.com, not ssh.visualstudio.com

### CODE REVIEW

**Comment by congyiwu** [comment]
@chcomley I messed up the domain in the last batch of edits I proposed

**Comment by chcomley** [comment]
@KathrynEE is someone still copying over vsts-docs to azure-devops-docs?

**Comment by steved0x** [comment]
Is this still a valid PR? I am following up.

**Comment by steved0x** [comment]
> @KathrynEE Kathryn Elliott FTE is someone still copying over vsts-docs to azure-devops-docs?

@chcomley No, just from azure-devops-docs-pr

**Comment by chcomley** [comment]
@steved0x Did this PR actually merge? @congyiwu Thanks for your fix - we are no longer using this repo. I don't believe this will be published. Please use azure-devops-docs-pr. Thanks!

**Comment by congyiwu** [comment]
@chcomley @steved0x somehow, this change is visible at https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#ssh-connections

Also, that page's Edit link points to https://github.com/MicrosoftDocs/**vsts-docs**/blob/master/docs/organizations/security/allow-list-ip-url.md

The View on GitHub link points to https://github.com/MicrosoftDocs/**vsts-docs**/issues?utf8=%E2%9C%93&q=%22d621620a-c924-03b1-8b43-f99c33e58bb8%22&in=body

If everyone is supposed to use **azure-devops-docs-pr** from now on, can y'all update the links in the published docs site?

**Pull request merged**
