### PR TITLE
Add details of encryption at rest

### PR DESCRIPTION
**Pull request by gitstua**
The encryption at rest information was publicly blogged as per https://devblogs.microsoft.com/devops/visual-studio-team-services-encryption-at-rest/ however not reflected in this page.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@gitstua : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gitstua** [comment]
re-submit PR shortly

**Comment by PRMerger13** [comment]
@gitstua : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@gitstua : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msdnguy** [comment]
It would be nice if this was added to https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops as an addendum to blob storage and SQLDB

**Comment by PRMerger13** [comment]
@gitstua : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
