### PR TITLE
Update appsettings.json typo

### PR DESCRIPTION
**Pull request by WestDiscGolf**
Fix typo

### CODE REVIEW

**Comment by alexhomer1** [comment]
Fix has been applied to source docs and will be published within 48 hours.

**Comment by WestDiscGolf** [comment]
Cool!

**Comment by steved0x** [comment]
@WestDiscGolf Thanks for your contribution, I am merging this in now for Alex.

**Comment by WestDiscGolf** [comment]
@steved0x Cheers!

**Pull request merged**
