### PR TITLE
Update test-glossary.md

### PR DESCRIPTION
**Pull request by Jteve-Sobs**
According to the source code of TestCaseResult, one outcome was missing. 'In progress' is listed there.
In addition the count of the outcomes was incorrect.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Jteve-Sobs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jteve-Sobs** [comment]
This is written as a comment in the source code at Microsoft.TeamFoundation.TestManagement.WebApi in the class TestCaseResult:

`   //     Summary:
    //     Test outcome of test result. Valid values = (Unspecified, None, Passed, Failed,
    //     Inconclusive, Timeout, Aborted, Blocked, NotExecuted, Warning, Error, NotApplicable,
    //     Paused, InProgress, NotImpacted)
    [DataMember(IsRequired = false, EmitDefaultValue = false)]
    public string Outcome;`

**Comment by ramiMSFT** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@ramiMSFT: I'm sorry - only the author of this article, @vinodjo, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Jteve-Sobs** [comment]
Is @vinodjo still active?

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
