### PR TITLE
Updated alternate credentials notice

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
I updated the alternate credentials notice, since the transition phase is over and alternate credentials do not work anymore.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@SebastianSchuetze : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mijacobs** [comment]
It looks like this belongs to @chcomley

**Comment by chcomley** [comment]
Thanks so much, @SebastianSchuetze!

#sign-off

**Comment by PRMerger16** [comment]
@chcomley: I'm sorry - only the author of this article, @mijacobs, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by cxwtool** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@cxwtool: I'm sorry - only the author of this article, @mijacobs, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mijacobs** [comment]
#sign-off

**Comment by chcomley** [comment]
Hi @mijacobs, I've approved this PR, but it looks like we need your sign off please.

**Pull request merged**
