### PR TITLE
Fix incorrectly encoded mdash

### PR DESCRIPTION
**Pull request by James-Jackson-South**
Second line change was automatic (possibly line endings?) and does not affect the output.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@James-Jackson-South : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Verified the update.

@James-Jackson-South Thanks for submitting this fix. It looks like the sentence should actually just end there, so I removed your correctly formatted em dash. Thanks again.

**Comment by James-Jackson-South** [comment]
Perfect. Even better. Thanks!

**Pull request merged**
