### PR TITLE
add inline code highlighting

### PR DESCRIPTION
**Pull request by spottedmahn**
related to #566 

I edit this via GitHub.  I'm pretty confident I didn't edit this:

image

Any thoughts as to why it is showing up?

### CODE REVIEW

**Comment by nschonni** [comment]
> Any thoughts as to why it is showing up?

There are some line ending issues in the repo. When you edit in the web, it normalizes a bunch of them in the edited file.

**Comment by spottedmahn** [comment]
>There are some line ending issues in the repo. When you edit in the web, it normalizes a bunch of them in the edited file.

😭

Is that being worked on?  Is there an issue in the [docs feedback repo](https://github.com/MicrosoftDocs/feedback/issues) for this?

So I'll have to clone and do it that way I guess?

**Comment by nschonni** [comment]
I wouldn't worry about redoing it unless someone actually from the project says something. Likely probably won't even cause a merge conflict if they end up bulk fixing the issue.

Thanks for pointing out the feedback repo!

**Comment by steved0x** [comment]
@spottedmahn @KathrynEE I'm closing this PR as the changes made in this PR (except for that odd character) have been incorporated in another internal PR with some other work, as described by Kathryn above. Thank you @spottedmahn for your contribution.

**Pull request closed without merging**
