### PR TITLE
Fixed a type for the Basic Features

### PR DESCRIPTION
**Pull request by mahajangaurav**
Fixed a minor typo in # Add users to your organization or project 
from: "* Five users who get [Basic features]" 
to   :  "* Free users who get [Basic features]"

### CODE REVIEW

**Comment by PRMerger6** [comment]
@mahajangaurav : Thanks for your contribution! The author, @chcomley, has been notified to review your proposed change.

**Comment by mahajangaurav** [comment]
Fixed a minor typo in # Add users to your organization or project
from: "* Five users who get [Basic features]"
to : "* Free users who get [Basic features]"

**Comment by chcomley** [comment]
Hi @mahajangaurav, thanks for your contribution, however the text reads as designed, "Five" users. Five (5) users get free Basic features. Thanks again!

**Comment by mahajangaurav** [comment]
> Hi @mahajangaurav, thanks for your contribution, however the text reads as designed, "Five" users. Five (5) users get free Basic features. Thanks again!

So sorry then. I misunderstood. Thanks for reviewing!

**Pull request closed without merging**
