### PR TITLE
Update artifacts-overview.md

### PR DESCRIPTION
**Pull request by compnerd**
Adjust the description for the build artifacts.  The PDB represents the artifacts for either a .NET based application (written in C# or other .NET language) or a C++ Windows application.  The previous wording implied a .NET application written in C++.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@compnerd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by compnerd** [comment]
A gentle ping on this

**Comment by ktoliver** [comment]
@chasewilson Could you review the proposed revision and indicate whether the PR is ready to merge? Thanks!

**Comment by compnerd** [comment]
@ktoliver ping

**Comment by compnerd** [comment]
@chasewilson @ktoliver ping

**Comment by ktoliver** [comment]
@steved0x @RoopeshNair  Would one of you be able to review this PR?

@compnerd I'm not a SME and can't merge the PR until it's approved by someone who works on the content. Thanks.

**Comment by ktoliver** [comment]
Thanks @RoopeshNair

**Comment by compnerd** [comment]
@ktoliver I understand.  The pings are to ensure that the change doesn't get lost in the volume :)

**Comment by compnerd** [comment]
@ktoliver @RoopeshNair @vijayma ping

**Comment by compnerd** [comment]
@ktoliver @RoopeshNair @vijayma ping?

**Comment by compnerd** [comment]
@ktoliver @RoopeshNair @vijayma ping x 3?

**Comment by compnerd** [comment]
@ktoliver @RoopeshNair @vijayma ping x 4?

**Comment by ktoliver** [comment]
@chcomley Would you be able to review this PR? Thanks.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@juliakm: I'm sorry - only the author of this article, @chasewilson, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@juliakm: I'm sorry - only the author of this article, @chasewilson, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by chasewilson** [comment]
#sign-off

**Pull request merged**
