### PR TITLE
Fix a typo in dotnet-core.md

### PR DESCRIPTION
**Pull request by GoldenCrystal**
Not much to say here

### CODE REVIEW

**Comment by PRMerger9** [comment]
@GoldenCrystal : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@GoldenCrystal : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@GoldenCrystal : Thanks for your contribution! The author, @andyjlewis, has been notified to review your proposed change.

**Comment by bahr2** [comment]
Most powerful source of Microsoft tech,  I have a question ,I need someone to give me the idea of making my private application to public and what kind of benefit could be?@bahr2

**Comment by steved0x** [comment]
This one has been fixed already, thank you for letting us know.

**Pull request closed without merging**
