### PR TITLE
task.json entry should be "categories"

### PR DESCRIPTION
**Pull request by anishkny**
If "category" is an array (instead of string), it fails verification when trying to upload to marketplace.

### CODE REVIEW

**Comment by nschonni** [comment]
This sounds like a bug in tfx-cli, since extensions can have multiple categories

**Comment by anishkny** [comment]
Thanks for the reply. Yeah actually I wasn’t sure what’s going on. Here is the issue I’m trying to solve:

https://developercommunity.visualstudio.com/comments/402932/view.html (Comment by me, Anish)

**Comment by nschonni** [comment]
Your extension is using "categories" instead of "category"

**Comment by anishkny** [comment]
@nschonni yes specifying `categories` instead of `category` in `task.json` seems to make my custom task show up in Pipelines! Yay it worked. Thanks!

**Comment by elbatk** [comment]
Hi @anishkny, so, it's my understanding that it should be "category" for the task.json, and "categories" for the extension manifest file. So you're saying that it should be "categories" for both?

**Comment by anishkny** [comment]
Actually I am also learning as I go - but it appears it should be `categories` for both `task.json` and `vss-extension.json` and both need to be array of strings.

In `task.json`, if its `catgeory: ['Azure Pipelines']`, it fails to validate upon uploading to Marketplace. Also if its `category: 'Azure Pipelines'` (a string), it doesn't show up while adding the custom task to a pipeline which wants to use it. 

It would be great to get official clarification from someone in MS 😺

**Comment by vtbassmatt** [comment]
@stephenmichaelf will you take a look at this one? I can fix the merge conflict if the content is correct.

**Comment by stephenmichaelf** [comment]
Ack. Please add me as reviewer so I don't lose track. Will take a look.

**Comment by vtbassmatt** [comment]
@stephenmichaelf can't seem to add you since you aren't a contributor on the repo. I added you, looks like you have to accept first.

**Comment by stephenmichaelf** [comment]
Done!

**Comment by PRMerger7** [comment]
@anishkny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by elbatk** [comment]
@stephenmichaelf I just got a ping on this one, let me know if there's anything I can help with

**Comment by ktoliver** [comment]
Hi @elbatk - The merge conflict appears to reflect the core question, so PR reviewers are not able to resolve it:

image

Could you indicate which is correct and then we will either merge the PR or close it, as relevant?

Thanks.

**Comment by PRMerger17** [comment]
@anishkny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by tfosmark** [comment]
@chcomley Can you help resolve this open question? TIA!

**Comment by vtbassmatt** [comment]
This change isn't correct. The schema is `category: string`. To make a task appear for Build or RM, you use `visibility: [ string ]` (whose legal values are `"Build"` and `"Release"`).

See [these examples](https://github.com/microsoft/azure-pipelines-tasks/search?l=JSON&q=category) from the in-box tasks.

**Pull request closed without merging**
