### PR TITLE
fix: MD038/no-space-in-code

### PR DESCRIPTION
**Pull request by nschonni**
- Spaces inside code span elements
- Replace inline code fence blocks with single backticks

### CODE REVIEW

**Comment by PRMerger14** [comment]
@nschonni : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@nschonni : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by steved0x** [comment]
@nschonni Sorry that it took us a while to get to this one and it has a merge conflict, if you resolve those 2 files I will merge it. Thank you!

**Comment by nschonni** [comment]
@steved0x i've rebase it now

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Pull request merged**
