### PR TITLE
Creating consistency with semicolons

### PR DESCRIPTION
**Pull request by castrodd**
At the beginning of the tutorial, there are no semicolons used in app.js; then, semicolons are used sporadically. I have removed all the semicolons to remain consistent throughout the file.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@castrodd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by castrodd** [comment]
@jborsecnik Any updates on whether this is being merged? The doc looks a bit haphazard switching back and forth between semicolons and no semicolons.

**Comment by ktoliver** [comment]
@apawast Could you review the proposed changes? Thanks!

**Comment by apawast** [comment]
@castrodd I still see a couple of semicolons in your update, are those needed?

**Comment by PRMerger14** [comment]
@castrodd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by castrodd** [comment]
@apawast Sorry for the long delay. I removed the remaining semicolons.

**Pull request merged**
