### PR TITLE
edit pass: buy-more-build-vs

### PR DESCRIPTION
**Pull request by ShawnJackson**
@chcomley – Please review the copy edit to this article and let me know if I’ve changed the technical meaning anywhere. This is for VSTS work request 1302753.

This article contains the line "We plan to remove the hosted XAML build controller from all organizations in the near future." Promises about future improvements are risky because they might not happen. Please make sure your legal contact has approved this information. If not, it would be safer to remove it.

### CODE REVIEW

**Comment by ShawnJackson** [comment]
@kasangi - Adding you for awareness.

**Comment by ShawnJackson** [comment]
Merge conflict fixed.

**Comment by ShawnJackson** [comment]
I changed the short form "Team Services" back to "VSTS," per our discussion in email.

**Review by chcomley — APPROVED** [review]

**Comment by chcomley** [comment]
@ShawnJackson, I approved this, however wanted to see if you could quickly replace the --s with - ? So, no double slashes? These are apparently not desired by my peers, so I just go with one - . Thanks

**Comment by ShawnJackson** [comment]
@chcomley - I made the change. The hyphen with spaces around it is against style guidelines, but I've heard that a real em dash (long dash) can cause problems in Markdown.

**Pull request merged**
