### PR TITLE
Removed traces of Bash task and improved formatting in Powershell task

### PR DESCRIPTION
**Pull request by ferenczy**

### CODE REVIEW

**Comment by vtbassmatt** [comment]
I must have screwed that up. I was pretty sure I fixed it before the rebrand. Thank you, @ferenczy !

**Comment by ferenczy** [comment]
@vtbassmatt How (and when) is it being deployed? There's still the old version on [docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=vsts).

**Comment by vtbassmatt** [comment]
@andyjlewis is this normal? I merged the commit 6 days ago (here on GitHub) but it hasn't published yet.

**Comment by vtbassmatt** [comment]
Argh. I must have gotten confused - apparently it wasn't in the PR I thought it was.

**Comment by andyjlewis** [comment]
After talking with @vtbassmatt I believe this issue is closed now.

**Comment by ferenczy** [comment]
@andyjlewis But when will it get deployed actually? Or how does the deployment process work?

**Comment by andyjlewis** [comment]
@ferenczy thanks for the heads up. There's a glitch between our branches. We're looking into it.

**Comment by andyjlewis** [comment]
I've finished the investigation and added fixing the issue to our backlog. Thanks for your patience on this one.

**Pull request merged**
