### PR TITLE
Note about UNIX permissions on Build artifacts

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Wish I had known this last night 😄

### CODE REVIEW

**Comment by chasewilson** [comment]
@ItalyPaleAle, Thanks for the contribution!
@elbatk, You mind verifying the information on this one?

**Comment by chasewilson** [comment]
@ItalyPaleAle There has been internal movement on this, I'm just giving this a bump @elbatk, you have any more information?

**Comment by PRMerger9** [comment]
@ItalyPaleAle : Thanks for your contribution! The author(s) have been notified to review your proposed change. @andyjlewis

**Comment by ktoliver** [comment]
Hi @chasewilson @elbatk - Could you indicate whether the PR can be merged? Thanks.

**Comment by juliakm** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@juliakm: I'm sorry - only the author of this article, @andyjlewis, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger9** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@juliakm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @juliakm Is this PR ready to merge?

**Comment by ktoliver** [comment]
The PR looks ready to merge, so we'll do that. :)

**Pull request merged**
