### PR TITLE
Update repos-slack.md

### PR DESCRIPTION
**Pull request by divais**
Fixes [AB#1666991](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1666991)

### CODE REVIEW

**Comment by PRMerger8** [comment]
@divais : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@steved0x: I'm sorry - only the author of this article, @RGKarthik, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
