### PR TITLE
Ordered lists number shouldn't be specified

### PR DESCRIPTION
**Pull request by spottedmahn**
You get that for free

### CODE REVIEW

**Comment by steved0x** [comment]
@spottedmahn Thank you for your contribution, I am sending it over to the right folks for review and will get back to you shortly.

**Comment by steved0x** [comment]
@spottedmahn I spoke with the author of this article, and we are publishing updates this week that will include changes to this article, so I am going to close the PR here to avoid conflicts. Thank you again for your contribution to our docs!

**Comment by spottedmahn** [comment]
I see, thanks for following up @steved0x!  I'll check back in a week to see the updates.

**Comment by spottedmahn** [comment]
Nice, I see the updates:

image

[Page reference](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance#lists)

**Pull request closed without merging**
