### PR TITLE
fix: MD003/heading-style/header-style

### PR DESCRIPTION
**Pull request by nschonni**
- ATX Heading style
- Space after --- in metadata causes parsing issues
- `----` inside moniker ranges without newlines get caught as Headers
- blank before metadata causes parsing issue

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author, @KathrynEE, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@nschonni : Thanks for your contribution! The author, @KathrynEE, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @KathrynEE, has been notified to review your proposed change.

**Comment by nschonni** [comment]
@KathrynEE I've rebased this for the conflicts

**Comment by KathrynEE** [comment]
@nschonni - Hi Nick - just seeing this and unfortunately there are again conflicts. If you can resolve the conflict, I'll go ahead and merge the PR.

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @KathrynEE, has been notified to review your proposed change.

**Pull request merged**
