### PR TITLE
Adding minor clarification on Preserve VNet parameter

### PR DESCRIPTION
**Pull request by JackStromberg**
Adding minor clarification on Preserve VNet parameter
https://github.com/MicrosoftDocs/vsts-docs/issues/4649

### CODE REVIEW

**Comment by PRMerger9** [comment]
@JackStromberg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
Note: There's  typo to fix.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Looks correct per https://github.com/MicrosoftDocs/vsts-docs/issues/4649#issuecomment-506239845. Merging.

**Pull request merged**
