### PR TITLE
chore: run `git add --renormalize .`

### PR DESCRIPTION
**Pull request by nschonni**
Probably better run on the internal repo, but it looks like the line endings have gotten overriden after the last cleanup when the .gitattributes got added.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @davidstaheli, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@nschonni : Thanks for your contribution! The author, @davidstaheli, has been notified to review your proposed change.

**Comment by KathrynEE** [comment]
@steved0x - Could you review and approve if you find this PR is OK.

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @davidstaheli, has been notified to review your proposed change.

**Comment by nschonni** [comment]
@steved0x it's probalby better you run the command in the title on the internal repo so you don't run into merge conflicts. I've confirmed that the files are still affected though

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @davidstaheli, has been notified to review your proposed change.

**Pull request merged**
