### PR TITLE
comments to yaml snippet given

### PR DESCRIPTION
**Pull request by auroraloop**
adding this as useful descriptions for customers to understand how pr triggers work. I'm a support engineer for Azure DevOps and we get a lot of support requests of customers claiming unexpected builds for pipelines containing pr triggers.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@auroraloop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@auroraloop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@auroraloop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by steved0x** [comment]
@auroraloop I made a few edits, and I'm merging this, thank you for your contribution.

**Comment by auroraloop** [comment]
@steved0x happy to help

**Pull request merged**
