### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@PRMerger17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Resolved merge conflict.

**Comment by PRMerger20** [comment]
@GitHubber17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@TedA-M : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@GitHubber17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@chcomley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chcomley** [comment]
#sign-off

**Comment by steved0x** [comment]
I'm merging this as the PRMerger team doesn't do repo sync

**Comment by steved0x** [comment]
#hold-off

**Comment by PRMerger14** [comment]
@megvanhuygen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@steved0x : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
