### PR TITLE
Add documentation about how YAML PR triggers only apply to GitHub

### PR DESCRIPTION
**Pull request by alancast**
According to [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger) article, the `pr` trigger in YAML build pipelines only applies to GitHub repos. 

Adding that to the documentation because I was confused why it wasn't working for me. If it does in fact apply to ADO repos (or any other git provider) then the other documentation should be updated.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@alancast : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@alancast : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@alancast : Thanks for your contribution! The author, @steved0x, has been notified to review your proposed change.

**Comment by alancast** [comment]
Closing this PR as the PR triggers also work for BitBucket. 

I'm unsure if the PR Triggers work for all git providers (in which case [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger) should be updated to reflect that), or all git providers other than azure devops, or just a few. Unfortunately I don't have time to figure out which one is the case, so closing this PR.

Though I do think someone who works with the PR trigger yaml code should update these docs as it's a little unclear how it works

**Pull request closed without merging**
