### PR TITLE
Several articles have been translated into Chinese

### PR DESCRIPTION
**Pull request by ltm0203**
Hello, do you have a repository in Chinese? Or build one?
I translated several articles, but found that he did not have a Chinese repository ?
How do I deal with and cooperate?

like it #740

### CODE REVIEW

**Comment by steved0x** [comment]
@ltm0203 Thank you for your contributions. I have sent an email to the author of this article to get more information on how to proceed and will let you know as soon as I get more informatio.

https://github.com/Microsoft/Localization/wiki/How-to-Contribute-to-docs.microsoft.com

**Comment by ltm0203** [comment]
@steved0x  ok,watting for good news

**Comment by ltm0203** [comment]
@terrysheng  This is  Tongming Liang ,Please see if you want to open a new Chinese version

**Comment by JasonCard** [comment]
Hi @ltm0203, 

Thank you very much for your contribution. 

Unfortunately, we are currently not supporting localization for this repository.
So we are not able to provide a Chinese repository for your contribution at this time.
I will certainly take this as your feedback for wanting this content to be localized in the future.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
cc @steved0x @SonjaSaltzman @Sara-Nicolini @terrysheng

**Pull request closed without merging**
