### PR TITLE
Update kubernetes.md

### PR DESCRIPTION
**Pull request by heoelri**
Added `useClusterAdmin` to the **Azure Resource Manager** section which wasn't documented here, yet. 

You can find the details here: 

* [KubernetesV1/task.json](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/task.json)
* [Kubernetes@1 - Support for admin credentials?](https://github.com/microsoft/azure-pipelines-tasks/issues/12427)
* [KubernetesV1/src/clusters/armkubernetescluster.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/src/clusters/armkubernetescluster.ts)

### CODE REVIEW

**Comment by PRMerger13** [comment]
@heoelri : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@azooinmyluggage - Could you review the proposed changes as the content owner/author? Thanks.

**Comment by ds-ms** [comment]
@heoelri could you fix the merge conflicts?

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ds-ms The merge conflict is resolved now.

**Comment by azooinmyluggage** [comment]
looks good

**Comment by ds-ms** [comment]
@ktoliver if you have write access, could you merge this PR?

**Pull request merged**
