### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@KathrynEE : Thanks for your contribution! The author, @KathrynEE, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@openpublishbuild : Thanks for your contribution! The author, @chcomley, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@openpublishbuild : Thanks for your contribution! The author, @KathrynEE, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@openpublishbuild : Thanks for your contribution! The author, @chcomley, has been notified to review your proposed change.

**Pull request merged**
