### PR TITLE
Docs typos2

### PR DESCRIPTION
**Pull request by nschonni**
Second pass with https://www.npmjs.com/package/cspell#Dictionaries with the following exceptions https://gist.github.com/nschonni/516b001b1bad688fcf4e294ec19745db

### CODE REVIEW

**Comment by steved0x** [comment]
@nschonni Thank you, can you remove this file from the PR:

docs/extend/get-started/visual-studio.md

And then I will merge.

Thanks,

Steve

**Comment by nschonni** [comment]
There are several commits on that file. If you comment on a particular line on the file itself I can try and remove it

**Comment by nschonni** [comment]
@steved0x I didn't remove all the changes, but I think I removed the part you wanted

**Comment by steved0x** [comment]
@nschonni I should have scrolled down further before I went looking - there were a couple of instances of "VSTF" that had been changed to "VSTS" and I wanted to check with the author. It looks like you got it because I can't seem to find it now. It looks like we have got some conflicts now, let me merge the rest of what I can get merged from the other PRs and then I'll take a look at these.

**Comment by nschonni** [comment]
no problem, think the merge conflicts are those weird encoding ones so I'll have to be careful rebasing. I'll give it a shot tonight when I'm home

**Comment by steved0x** [comment]
@nschonni There were some terminology changes that recently got made (Team Project->Project) and it was mostly those, I fixed up this one and the other one and I am merging them both.

**Pull request merged**
